destination:  _site/

plugins_dir:  _jekyll/_plugins
layouts_dir:  _jekyll/_layouts
includes_dir: _jekyll/_includes
data_dir:     _jekyll/_data

exclude: [ "_jekyll" ]

collections:
  assets:
    output: true

#Others
markdown: kramdown
# Setup
title:        IPSP PHP SDK
tagline:      Accept epayments on your website
baseurl:      /ipsp-php

author:
  name:       Stepan Kosatyi
  url:        http://www.kosatyi.com

buttons:
  github: https://github.com/kosatyi/ipsp-php
  zip: http://github.com/kosatyi/ipsp-php/archive/master.zip
  tar: http://github.com/kosatyi/ipsp-php/archive/master.tar.gz