gems:
  - jekyll-seo-tag
#Others
markdown: kramdown
# Setup
title:        IPSP PHP SDK
tagline:      Accept epayments on your website
baseurl:      /ipsp-php

author:
  name:       Stepan Kosatyi
  url:        http://www.kosatyi.com/

buttons:
  github: https://github.com/kosatyi/ipsp-php
  zip: http://github.com/kosatyi/ipsp-php/archive/master.zip
  tar: http://github.com/kosatyi/ipsp-php/archive/master.tar.gz

defaults:
  -
    scope:
        path: "docs"
        type: "pages"
    values:
        headline: "SDK Docs"
        description: "Ipsp Developer Documentation"
  -
    scope:
        path: "examples"
        type: "pages"
    values:
        headline: "Showcase"
        description: "ahdsgfahgs dfkjh gaks dhfgadfskjh"
  -
    scope:
        path: "modules"
        type: "pages"
    values:
        headline: "Components & Helpers"
        description: "ahdsgfahgs dfkjh gaks dhfgadfskjh"