gems:
  - jekyll-seo-tag
  - jekyll-sitemap
#Others
markdown: kramdown
# Setup
title:        IPSP PHP SDK
tagline:      Accept epayments on your website
baseurl:

styles:
  - main.css
  - ipsp.css

javascript:
  - jquery.js
  - jquery.ejs.js
  - jquery.connector.js
  - main.js
  - ipsp.js

# Seo
social:
  name: Stepan Kosatyi
  links:
    - https://twitter.com/kosatyi
    - https://www.facebook.com/Stepan.Kosatyi
    - https://www.linkedin.com/in/StepanKosatyi
    - https://plus.google.com/+StepanKosatyi
    - https://github.com/kosatyi


webmaster_verifications:
  google: ytqWppv3WHbrMA_P7TOtYHvti5LbegWZnv4s5JOaLBE
  bing: 1234
  alexa: 1234
  yandex: 1234

author: kosatyi

# Site variables
buttons:
  -
    name: View on GitHub
    link: https://github.com/kosatyi/ipsp-php
  -
    name: Download .zip
    link: http://github.com/kosatyi/ipsp-php/archive/master.zip
  -
    name: Download .tar.gz
    link: http://github.com/kosatyi/ipsp-php/archive/master.tar.gz

defaults:
  - scope:
      path: ""
    values:
      image:
        path:  /assets/images/default-card.png
        height: 100
        width: 100
  -
    scope:
        path: "docs"
        type: "pages"
    values:
        headline: "SDK Docs"
        description: "Ipsp Developer Documentation"
  -
    scope:
        path: "examples"
        type: "pages"
    values:
        headline: "Showcase"
        description: "Browse the showcase to see some of our favorite implementations"
  -
    scope:
        path: "modules"
        type: "pages"
    values:
        headline: "Components & Helpers"
        description: "Useful components for checkout development"
  -
    scope:
        path: "activation"
        type: "pages"
    values:
        headline: "Accept payments"
        description: "Accept VISA and MasterCard securely, quickly and easily on your website"