plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

port: 4002

baseurl:

navigation: true

remote_theme: kosatyi/sjt

brand: IPSP PHP
title: Payment SDK
description: Start e-commerce on your website.

# Seo
social:
  name: IPSP PHP SDK
  links:
    - https://www.facebook.com/ipsp.sdk/
    - https://twitter.com/ipspsdk/
    - https://plus.google.com/101483721165557150473
    - https://github.com/ipsp-php/ipsp-php
    - https://packagist.org/packages/ipsp-php/ipsp-php
    - https://libraries.io/packagist/ipsp-php/ipsp-php

twitter:
  username: ipspsdk

facebook:
  publisher: https://www.facebook.com/ipsp.sdk/

webmaster_verifications:
  google: ytqWppv3WHbrMA_P7TOtYHvti5LbegWZnv4s5JOaLBE


author:
  name: Stepan Kosatyi
  url: https://kosatyi.com/

toolbar:
  -
    name: Docs
    link: /docs/
  -
    name: Signup/Signin
    link: https://portal.fondy.eu/

github:
  repository_url: https://github.com/ipsp-php/ipsp-php