destination:  _site/
plugins_dir:  jekyll/_plugins
layouts_dir:  jekyll/_layouts
includes_dir: jekyll/_includes
data_dir:     jekyll/_data

include: ["jekyll/assets/css/main.css","jekyll/assets/js/main.js"]
#exclude:
#  - jekyll/


#Others
markdown: kramdown
# Setup
title:        IPSP PHP SDK
tagline:      Accept epayments on your website
baseurl:      /ipsp-php
paginate:     1

author:
  name:       Stepan Kosatyi
  url:        http://www.kosatyi.com

buttons:
  github: https://github.com/kosatyi/ipsp-php
  zip: http://github.com/kosatyi/ipsp-php/archive/master.zip
  tar: http://github.com/kosatyi/ipsp-php/archive/master.tar.gz