destination:  _site/
plugins_dir:  sjt/_plugins/
layouts_dir:  sjt/_layouts/
includes_dir: sjt/_includes/
exclude:
  - sjt/

#Others
markdown: kramdown
# Setup
title:        IPSP PHP SDK
tagline:      Accept epayments on your website
baseurl:      /ipsp-php
paginate:     1

author:
  name:       Stepan Kosatyi
  url:        http://www.kosatyi.com

buttons:
  github: https://github.com/kosatyi/ipsp-php
  zip: http://github.com/kosatyi/ipsp-php/archive/master.zip
  tar: http://github.com/kosatyi/ipsp-php/archive/master.tar.gz