# Setup
title:        IPSP PHP SDK
tagline:      Accept epayments on your website
baseurl:      ""
paginate:     1
layout : default
# About/contact
author:
  name:       Stepan Kosatyi
  url:        http://www.kosatyi.com
url:
  github:
  zip:
  tar:
# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown