# Setup
title:        IPSP PHP SDK
tagline:      Payment service provider SDK Accept purchase
baseurl:      ""
paginate:     1
layout : default
# About/contact
author:
  name:       Stepan Kosatyi
  url:        http://www.kosatyi.com

# Gems
gems:
  - jekyll-paginate


#Others
markdown: kramdown