source:       ./public
destination:  ./.build
plugins_dir:  _plugins
layouts_dir:  _layouts
data_dir:     _data
includes_dir: _includes

# Gems
gems:
  - jekyll-paginate
  - jekyll-sitemap

#Others
markdown: kramdown

# Setup
title:        IPSP PHP SDK
tagline:      Accept epayments on your website
baseurl:      ""
paginate:     1

author:
  name:       Stepan Kosatyi
  url:        http://www.kosatyi.com

url:
  github:
  zip:
  tar:
