# Gems
gems:
  - jekyll-paginate
  - jekyll-sitemap

#Others
markdown: kramdown

# Setup
title:        IPSP PHP SDK
tagline:      Accept epayments on your website
baseurl:      ""
paginate:     1

author:
  name:       Stepan Kosatyi
  url:        http://www.kosatyi.com

url:
  github:
  zip:
  tar:
